from typing import Protocol

from simple_service.domain import Order, Product


class ProductRepository(Protocol):
    async def add(self, product: Product) -> Product: ...

    async def get(self, product_id: str) -> Product: ...

    async def receive(self, product_id: str, quantity: int) -> Product: ...

    async def reserve(self, product_id: str, quantity: int) -> Product: ...

    async def release(self, product_id: str, quantity: int) -> Product: ...


class OrderRepository(Protocol):
    async def add(self, order: Order) -> Order: ...

    async def get(self, order_id: str) -> Order: ...

    async def cancel(self, order_id: str) -> Order: ...


class MovementRepository(Protocol):
    async def record(self, kind: str, values: dict[str, object]) -> None: ...

